apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: attestguard-quarantine
  namespace: default
spec:
  podSelector:
    matchLabels:
      quarantine: "true"
  policyTypes:
    - Ingress
    - Egress
  ingress: [] # Deny all ingress
  egress: []  # Deny all egress
